name: Build Bilix

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        apkname: [Bilix-8.6.0,Bilix-global-3.19.2]  #List of original apk
    env:
      # build need
      Build-Bilix: true
      Build-Bilix-global: true
      # Check ver
      Bilix-ver: 8.6.0
      Bilix-global-ver: 3.19.2
      Bilix-vercode: 8060200
      Bilix-global-vercode: 7750600
      # torelease
      Bilix-torelease: true
      Bilix-global-torelease: true
      # Changelog need
      push-Changelog: false
      # release type
      Bilix-draft: false
      Bilix-prerelease: true
      Bilix-global-draft: false
      Bilix-global-prerelease: true
      # name
      apkfile: ${{ matrix.apkname }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      # Get $publishTime
      - name: Get Current Time
        run: |
          TIME=$EPOCHSECONDS
          echo "TIME=$TIME" >> $GITHUB_ENV

      - name: Setup JRE
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          java-package: 'jre'

      - name: Get build resource
        run: |
          echo Downloading CI zip
          git clone --recurse-submodules https://github.com/sti-233/BiliRoamingX.git
          cp -r ./BiliRoamingX/* ./
          echo Downloading modified revanced-cli
          wget https://github.com/zjns/revanced-cli/releases/download/v4.6.0.1/revanced-cli.jar

      - name: Cat commit ids
        run: |
          echo "old-commit-id=$(cat old-commit-id.txt)" >> $GITHUB_ENV

      # Get BiliRoamingX ci Changelog
      - name: Get Changelog from commits
        if: ${{ env.push-Changelog == 'true' }}
        run: |
          wget https://github.com/sti-233/BiliRoamingX/compare/${{ env.old-commit-id }}...main
          mv ${{ env.old-commit-id }}...main commit-resource.txt
          results=$(grep -rHn '<a class="Link--primary text-bold js-navigation-open markdown-title" href="/sti-233/BiliRoamingX/commit/' commit-resource.txt)
          echo "$results" | while IFS=: read -r filename lineno content; do
            end_line=$((lineno + 30))
            lines=$(sed -n "${lineno},${end_line}p" "$filename")
            if echo "$lines" | grep -q "@zjns"; then
              getlog=$(echo "$content" | sed -n 's/.*<a class="Link--primary text-bold js-navigation-open markdown-title" href="\/sti-233\/BiliRoamingX\/commit\/[^"]*">\([^<]*\)<\/a>.*/\1/p')
              if [ -n "$getlog" ]; then
                echo -e " - $getlog " >> Changelog.txt
                cat Changelog.txt
              fi
            fi
          done

      - name: val empty to Changelog
        if: ${{ env.push-Changelog == 'false' }}
        run: echo -e " - no changlog now " >> Changelog.txt

      # Check version is cn or play
      - name: Is Bilix?
        run: echo "Is-Bilix=$(if [ '${{ env.apkfile }}' == 'Bilix-${{ env.Bilix-ver }}' ]; then echo true; else echo false; fi)" >> $GITHUB_ENV

      - name: Is Bilix-global?
        run: echo "Is-Bilix-global=$(if [ '${{ env.apkfile }}' == 'Bilix-global-${{ env.Bilix-global-ver }}' ]; then echo true; else echo false; fi)" >> $GITHUB_ENV

      # Get original bilibili
      - name: Get bilibili
        if: ${{ env.Is-Bilix == 'true' }}
        run: |
          aria2c --out "${{ env.apkfile }}.apk" https://m.wandoujia.com/apps/281291/download/

      - name: Get bilibili-global
        if: ${{ env.Is-Bilix-global == 'true' }}
        run: aria2c --out "${{ env.apkfile }}.apk" https://d.apkpure.com/b/APK/com.bilibili.app.in?version=latest

      # Check $version & $versionCode
      - name: "Get Apk Info"
        id: "apk-info"
        uses: "8Mi-Tech/get-apk-info-action@master"
        with:
          apkPath: "${{ env.apkfile }}.apk"
        #版本号：${{steps.apk-info.outputs.versionNum}}
        #版本代码：${{steps.apk-info.outputs.versionCode}}

      - name: Check Bilibili ver
        if: ${{ env.Is-Bilix == 'true' }}
        run: |
          if [ "${{ steps.apk-info.outputs.versionCode }}" == "${{ env.Bilix-vercode }}" ]; then
            echo "correctVersionCode=true" >> $GITHUB_ENV
          else
            echo "correctVersionCode=false" >> $GITHUB_ENV
          fi
          if [ "${{ steps.apk-info.outputs.versionNum }}" == "${{ env.Bilix-ver }}" ]; then
            echo "correctVersion=true" >> $GITHUB_ENV
          else
            echo "correctVersion=false" >> $GITHUB_ENV
          fi

      - name: Check Bilibili-global ver
        if: ${{ env.Is-Bilix-global == 'true' }}
        run: |
          if [ "${{ steps.apk-info.outputs.versionCode }}" == "${{ env.Bilix-global-vercode }}" ]; then
            echo "correctVersionCode=true" >> $GITHUB_ENV
          else
            echo "correctVersionCode=false" >> $GITHUB_ENV
          fi
          if [ "${{ steps.apk-info.outputs.versionNum }}" == "${{ env.Bilix-global-ver }}" ]; then
            echo "correctVersion=true" >> $GITHUB_ENV
          else
            echo "correctVersion=false" >> $GITHUB_ENV
          fi

      - name: Check is Bilibili correct ver
        run: |
          if [ "${{ env.correctVersionCode }}" == "true" ] && [ "${{ env.correctVersion }}" == "true" ]; then
            echo "correctVer=true" >> $GITHUB_ENV
          else
            echo "correctVer=false" >> $GITHUB_ENV
          fi

      # Get $patchVersion
      - name: Get version
        run: echo "ver=$(cat version.txt)" >> $GITHUB_ENV

      # Get $patchVersionCode
      - name: Get bigver
        run: |
          getbigver=$(echo ${{ env.ver }} | cut -d '.' -f 1-3)
          bigver=$(echo "$getbigver" | awk -F. '{printf "%d0%d00%d\n", $1, $2, $3}')
          echo "bigver=$bigver" >> $GITHUB_ENV

      # get build resource in ci zip
      - name: Unzip CI zip and Rename
        run: |
          unzip BiliRoamingX-CI-Build.zip
          mv BiliRoamingX-integrations-${{ env.ver }}.apk integrations.apk
          mv BiliRoamingX-patches-${{ env.ver }}.jar patches.jar

      # build part
      - name: Build Bilix
        if: ${{ env.Is-Bilix == 'true' && env.Build-Bilix == 'true' && env.correctVer == 'true'  }}
        run: java -jar revanced-cli.jar patch --merge integrations.apk --patch-bundle patches.jar --signing-levels 1,2,3 ${{ env.apkfile }}.apk

      - name: Build Bilix-global
        if: ${{ env.Is-Bilix-global == 'true' && env.Build-Bilix-global == 'true' && env.correctVer == 'true'  }}
        run: java -jar revanced-cli.jar patch --merge integrations.apk --patch-bundle patches.jar --signing-levels 1,2,3 ${{ env.apkfile }}.apk

      # named Bilix
      - name: Rename Bilix
        if: ${{ env.Is-Bilix == 'true' && env.Build-Bilix == 'true' && env.correctVer == 'true'  }}
        run: mv ${{ env.apkfile }}-patched.apk ${{ env.apkfile }}-${{ env.ver }}@Aniruf_x.apk

      - name: Rename Bilix-global
        if: ${{ env.Is-Bilix-global == 'true' && env.Build-Bilix-global == 'true' && env.correctVer == 'true'  }}
        run: mv ${{ env.apkfile }}-patched.apk ${{ env.apkfile }}-${{ env.ver }}@Aniruf_x.apk

      # push Bilix to ci
      - name: Upload Bilix (CI)
        if: ${{ env.Is-Bilix == 'true' && env.Build-Bilix == 'true' && env.correctVer == 'true'  }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.apkfile }}-${{ env.ver }}@Aniruf_x.apk
          path: ./${{ env.apkfile }}-${{ env.ver }}@Aniruf_x.apk

      - name: Upload Bilix-global (CI)
        if: ${{ env.Is-Bilix-global == 'true' && env.Build-Bilix-global == 'true' && env.correctVer == 'true'  }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.apkfile }}-${{ env.ver }}@Aniruf_x.apk
          path: ./${{ env.apkfile }}-${{ env.ver }}@Aniruf_x.apk

      # Get $sn
      - name: Get sn from Bilix
        if: ${{ env.Is-Bilix == 'true' && env.Build-Bilix == 'true' && env.correctVer == 'true' }}
        run: |
          sudo apt-get install aapt
          aapt dump xmltree ./${{ env.apkfile }}-${{ env.ver }}@Aniruf_x.apk AndroidManifest.xml > AndroidManifest_output.txt
          sn_value=$(grep "BUILD_SN" ./AndroidManifest_output.txt -A 1 | grep "android:value" | cut -d'=' -f2 | cut -d')' -f2 | awk '{printf "%d\n", strtonum($1)}')
          echo "sn=$sn_value" >> $GITHUB_ENV

      - name: Get sn from Bilix-global
        if: ${{ env.Is-Bilix-global == 'true' && env.Build-Bilix-global == 'true' && env.correctVer == 'true'  }}
        run: |
          sudo apt-get install aapt
          aapt dump xmltree ./${{ env.apkfile }}-${{ env.ver }}@Aniruf_x.apk AndroidManifest.xml > AndroidManifest_output.txt
          sn_value=$(grep "BUILD_SN" ./AndroidManifest_output.txt -A 1 | grep "android:value" | cut -d'=' -f2 | cut -d')' -f2 | awk '{printf "%d\n", strtonum($1)}')
          echo "sn=$sn_value" >> $GITHUB_ENV

      # Get $md5
      - name: Get md5 from Bilix
        if: ${{ env.Is-Bilix == 'true' && env.Build-Bilix == 'true' && env.correctVer == 'true'  }}
        run: |
          md5=$(md5sum ./${{ env.apkfile }}-${{ env.ver }}@Aniruf_x.apk | cut -d ' ' -f 1)
          echo "md5=$md5" >> $GITHUB_ENV

      - name: Get md5 from Bilix-global
        if: ${{ env.Is-Bilix-global == 'true' && env.Build-Bilix-global == 'true' && env.correctVer == 'true'  }}
        run: |
          md5=$(md5sum ./${{ env.apkfile }}-${{ env.ver }}@Aniruf_x.apk | cut -d ' ' -f 1)
          echo "md5=$md5" >> $GITHUB_ENV

      # Get $size
      - name: Get size from Bilix
        if: ${{ env.Is-Bilix == 'true' && env.Build-Bilix == 'true' && env.correctVer == 'true'  }}
        run: |
          size=$(stat -c %s ./${{ env.apkfile }}-${{ env.ver }}@Aniruf_x.apk)
          echo "size=$size" >> $GITHUB_ENV

      - name: Get size from Bilix-global
        if: ${{ env.Is-Bilix-global == 'true' && env.Build-Bilix-global == 'true' && env.correctVer == 'true'  }}
        run: |
          size=$(stat -c %s ./${{ env.apkfile }}-${{ env.ver }}@Aniruf_x.apk)
          echo "size=$size" >> $GITHUB_ENV

      # Release part
      - name: Release Bilix
        if: ${{ env.Is-Bilix == 'true' && env.Bilix-torelease == 'true' && env.correctVer == 'true' && env.Build-Bilix == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          draft: ${{ env.Bilix-draft }}
          prerelease: ${{ env.Bilix-prerelease }}
          fail_on_unmatched_files: true
          name: 'Bilix ${{ env.Bilix-ver }}(${{ env.Bilix-vercode }}) with BiliroamingX ${{ env.ver }}'
          tag_name: 'android-v${{ env.Bilix-ver }}-b${{ env.sn }}-p${{ env.ver }}'
          body: |
            版本信息：${{ env.Bilix-ver }} ${{ env.Bilix-vercode }} ${{ env.ver }} ${{ env.bigver }} ${{ env.sn }} ${{ env.size }} ${{ env.md5 }} ${{ env.TIME }}
             > 合并主分支
             > Bump bili ver to ${{ env.Bilix-vercode }}
            $(cat Changelog.txt)
          files: ./Bilix-${{ env.Bilix-ver }}-${{ env.ver }}@Aniruf_x.apk
        continue-on-error: true

      - name: Release Bilix-global
        if: ${{ env.Is-Bilix-global == 'true' && env.Bilix-global-torelease == 'true' && env.correctVer == 'true' && env.Build-Bilix-global == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          draft: ${{ env.Bilix-global-draft }}
          prerelease: ${{ env.Bilix-global-prerelease }}
          fail_on_unmatched_files: true
          name: 'Bilix global ${{ env.Bilix-global-ver }}(${{ env.Bilix-global-vercode }}) with BiliroamingX ${{ env.ver }}'
          tag_name: 'android_i-v${{ env.Bilix-global-ver }}-b${{ env.sn }}-p${{ env.ver }}'
          body: |
            版本信息：${{ env.Bilix-global-ver }} ${{ env.Bilix-global-vercode }} ${{ env.ver }} ${{ env.bigver }} ${{ env.sn }} ${{ env.size }} ${{ env.md5 }} ${{ env.TIME }}
             > 合并主分支
             > Bump bili ver to ${{ env.Bilix-global-vercode }}
            $(cat Changelog.txt)
          files: ./Bilix-global-${{ env.Bilix-global-ver }}-${{ env.ver }}@Aniruf_x.apk
        continue-on-error: true

      # output Bilix informations
      - name: Build Bilix Success
        if: ${{ env.Is-Bilix == 'true' && env.Build-Bilix == 'true' && env.correctVer == 'true'  }}
        run: |
          echo "### Build Bilix Success" >> $GITHUB_STEP_SUMMARY
          echo "版本信息：${{ env.Bilix-ver }} ${{ env.Bilix-vercode }} ${{ env.ver }} ${{ env.bigver }} ${{ env.sn }} ${{ env.size }} ${{ env.md5 }} ${{ env.TIME }}" >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
          echo " > 合并主分支" >> $GITHUB_STEP_SUMMARY
          echo " > Bump bili ver to ${{ env.Bilix-global-vercode }}" >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
          echo "$(cat Changelog.txt)" >> $GITHUB_STEP_SUMMARY
        continue-on-error: true

      - name: Build Bilix-global Success
        if: ${{ env.Is-Bilix-global == 'true' && env.Build-Bilix-global == 'true' && env.correctVer == 'true'  }}
        run: |
          echo "### Build Bilix-global Success" >> $GITHUB_STEP_SUMMARY
          echo "版本信息：${{ env.Bilix-global-ver }} ${{ env.Bilix-global-vercode }} ${{ env.ver }} ${{ env.bigver }} ${{ env.sn }} ${{ env.size }} ${{ env.md5 }} ${{ env.TIME }}" >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
          echo " > 合并主分支" >> $GITHUB_STEP_SUMMARY
          echo " > Bump bili ver to ${{ env.Bilix-global-vercode }}" >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
          echo "$(cat Changelog.txt)" >> $GITHUB_STEP_SUMMARY
        continue-on-error: true

      - name: End
        run: echo "Build end."