name: Build Bilix

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        apkname: [Bilix-8.6.0, Bilix-global-3.19.2]  # List of vanilla apk
    env:
      ver: 1.22.5.r1923  # the billroamingX version
      # run-id: 10026067422
      bigver: 1.22.5
      Bilix-vercode: 8060100
      Bilix-global-vercode: 7750600
      Bilix-ver: 8.6.0
      Bilix-global-ver: 3.19.2
      Bilix-sn: 15467355
      Bilix-global-sn: 15154452
      Bilix-torelease: false
      Bilix-draft: true
      Bilix-prerelease: false
      Bilix-global-torelease: true
      Bilix-global-draft: false
      Bilix-global-prerelease: true
    runs-on: ubuntu-latest
    steps:
    
      - name: Get Current Time
        run: |
          TIME=$EPOCHSECONDS
          echo "TIME=$TIME" >> $GITHUB_ENV
          
      - name: Setup JRE
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          java-package: 'jre'
          
      - name: Get resource
        run: |
          echo Downloading original apk
          wget https://github.com/sti-233/Bilix-PreBuilds/releases/download/original/${{ matrix.apkname }}.apk
          echo Downloading modified revanced-cli
          wget https://github.com/zjns/revanced-cli/releases/download/v4.6.0.1/revanced-cli.jar
          
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Get BiliroamingX CI Artifact URL
        id: get_artifact_url
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const run_id = ${{ env.run-id }};
            const artifactName = `BiliRoamingX-${{ env.ver }}.zip`;
            const token = ${{ secrets.CUSTOM_GITHUB_TOKEN }};
            const artifacts = await github.actions.listWorkflowRunArtifacts({
              owner: 'sti-233',
              repo: 'BiliroamingX',
              run_id: run_id
            });
            const artifact = artifacts.data.artifacts.find(a => a.name === artifactName);
            if (!artifact) {
              throw new Error(`Artifact ${artifactName} not found`);
            }
            return artifact.archive_download_url;

      - name: Download BiliroamingX CI Artifact
        run: curl -L -o BiliRoamingX-${{ env.ver }}.zip -H "Authorization: token ${{ secrets.CUSTOM_GITHUB_TOKEN }}" ${{ steps.get_artifact_url.outputs.result }}
          
      - name: Unzip CI zip and Rename
        run: |
          unzip BiliRoamingX-${{ env.ver }}.zip
          mv BiliRoamingX-integrations-${{ env.ver }}.apk integrations.apk
          mv BiliRoamingX-patches-${{ env.ver }}.jar patches.jar
          
      - name: Build Bilix
        run: java -jar revanced-cli.jar patch --merge integrations.apk --patch-bundle patches.jar --signing-levels 1,2,3 ${{ matrix.apkname }}.apk
        
      - name: Rename Bilix
        run: mv ${{ matrix.apkname }}-patched.apk ${{ matrix.apkname }}-${{ env.ver }}@Aniruf_x.apk
        
      - name: Upload Bilix (CI)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.apkname }}-${{ env.ver }}@Aniruf_x.apk
          path: ./${{ matrix.apkname }}-${{ env.ver }}@Aniruf_x.apk
          
      - name: Get sn from Bilix
        run: |
          cp ./${{ matrix.apkname }}-${{ env.ver }}@Aniruf_x.apk ./${{ matrix.apkname }}_patched.zip
          unzip ./${{ matrix.apkname }}_patched.zip
          mv AndroidManifest.xml ${{ matrix.apkname }}-AndroidManifest.xml
            
      - name: Upload sn-AndroidManifest.xml (CI)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.apkname }}-AndroidManifest.xml
          path: ./${{ matrix.apkname }}-AndroidManifest.xml
          
      - name: Get md5 from Bilix
        run: |
          md5=$(md5sum ./${{ matrix.apkname }}-${{ env.ver }}@Aniruf_x.apk | cut -d ' ' -f 1)
          echo "md5=$md5" >> $GITHUB_ENV
          
      - name: Get size from Bilix
        run: |
          size=$(stat -c %s ./${{ matrix.apkname }}-${{ env.ver }}@Aniruf_x.apk)
          echo "size=$size" >> $GITHUB_ENV
          
      - name: Is Bilix?
        run: echo "Is-Bilix=$(if [ '${{ matrix.apkname }}' == 'Bilix-${{ env.Bilix-ver }}' ]; then echo true; else echo false; fi)" >> $GITHUB_ENV
        
      - name: Is Bilix-global?
        run: echo "Is-Bilix-global=$(if [ '${{ matrix.apkname }}' == 'Bilix-global-${{ env.Bilix-global-ver }}' ]; then echo true; else echo false; fi)" >> $GITHUB_ENV
          
      - name: Release Bilix
        if: ${{ env.Bilix-torelease == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          draft: ${{ env.Bilix-draft }}
          prerelease: ${{ env.Bilix-prerelease }}
          fail_on_unmatched_files: true
          name: 'Bilix ${{ env.Bilix-ver }}(${{ env.Bilix-vercode }}) with BiliroamingX ${{ env.ver }}'
          tag_name: 'android-v${{ env.Bilix-ver }}-b${{ env.Bilix-sn }}-p${{ env.ver }}'
          body: '版本信息：${{ env.Bilix-ver }} ${{ env.Bilix-vercode }} ${{ env.ver }} ${{ env.bigver }} ${{ env.Bilix-sn }} ${{ env.size }} ${{ env.md5 }} ${{ env.TIME }}'
          files: ./Bilix-${{ env.Bilix-ver }}-${{ env.ver }}@Aniruf_x.apk
        continue-on-error: true
            
      - name: Release Bilix-global
        if: ${{ env.Bilix-global-torelease == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          draft: ${{ env.Bilix-global-draft }}
          prerelease: ${{ env.Bilix-global-prerelease }}
          fail_on_unmatched_files: true
          name: 'Bilix global ${{ env.Bilix-global-ver }}(${{ env.Bilix-global-vercode }}) with BiliroamingX ${{ env.ver }}'
          tag_name: 'android_i-v${{ env.Bilix-global-ver }}-b${{ env.Bilix-global-sn }}-p${{ env.ver }}'
          body: '版本信息：${{ env.Bilix-global-ver }} ${{ env.Bilix-global-vercode }} ${{ env.ver }} ${{ env.bigver }} ${{ env.Bilix-global-sn }} ${{ env.Bilix-size }} ${{ env.md5 }} ${{ env.TIME }}'
          files: ./Bilix-global-${{ env.Bilix-global-ver }}-${{ env.ver }}@Aniruf_x.apk
        continue-on-error: true
            
      - name: Build Bilix Success
        if: ${{ env.Is-Bilix == 'true' }}
        run: echo "### Build Bilix Success<br/>版本信息：${{ env.Bilix-ver }} ${{ env.Bilix-vercode }} ${{ env.ver }} ${{ env.bigver }} ${{ env.Bilix-sn }} ${{ env.size }} ${{ env.md5 }} ${{ env.TIME }}" >> $GITHUB_STEP_SUMMARY
        continue-on-error: true
        
      - name: Build Bilix-global Success
        if: ${{ env.Is-Bilix-global == 'true' }}
        run: echo "### Build Bilix-global Success<br/>版本信息：${{ env.Bilix-global-ver }} ${{ env.Bilix-global-vercode }} ${{ env.ver }} ${{ env.bigver }} ${{ env.Bilix-global-sn }} ${{ env.Bilix-size }} ${{ env.md5 }} ${{ env.TIME }}" >> $GITHUB_STEP_SUMMARY
        continue-on-error: true
        
      - name: End
        run: echo "Build end."