name: Recompose BiliRoamingX

on:
  workflow_dispatch:

jobs:
  Recompose-BiliRoamingX:
    name: Recompose BiliRoamingX
    runs-on: ubuntu-latest
    steps:
      # Check repo
      - name: Checkout code
        uses: actions/checkout@v4
      # Get resource
      - name: Recompose BiliRoamingX
        run: |
          git clone --recurse-submodules https://github.com/BiliRoamingX/BiliRoamingX.git
          cd ./
          git clone https://github.com/sti-233/Bilix-PreBuilds.git
          cp ./Bilix-PreBuilds/Merge-Resource/biliroaming_setting_custom_update_source.xml ./BiliRoamingX/patches/src/main/resources/bilibili/xml/biliroaming_setting_custom_update_source.xml
          cp ./Bilix-PreBuilds/Merge-Resource/Upgrade.kt ./BiliRoamingX/integrations/app/src/main/java/app/revanced/bilibili/patches/okhttp/hooks/Upgrade.kt
          rm ./Bilix-PreBuilds/Merge-Resource/Build.prop
          rm ./Bilix-PreBuilds/Merge-Resource/biliroaming_setting_custom_update_source.xml
          rm ./Bilix-PreBuilds/Merge-Resource/Upgrade.kt
          cp ./Bilix-PreBuilds/Merge-Resource/* ./BiliRoamingX
          echo "-"
          echo "./BiliRoamingX/patches/src/main/resources/bilibili/host/values/strings.xml"
          echo "-"
          sed -i '/    <string name="biliroaming_settings_title">哔哩漫游X<\/string>/c\    <string name="biliroaming_settings_title">BiliRoamingX<\/string>' ./BiliRoamingX/patches/src/main/resources/bilibili/host/values/strings.xml
          sed -i '/    <string name="biliroaming_toast_prefix">哔哩漫游X：<\/string>/c\    <string name="biliroaming_toast_prefix">BiliRoamingX：<\/string>' ./BiliRoamingX/patches/src/main/resources/bilibili/host/values/strings.xml
          sed -i '/    <string name="biliroaming_custom_update_summary">允许APP检查作者官方项目提供的预构建漫游X集成包更新<\/string>/c\    <string name="biliroaming_custom_update_summary">允许APP检查本Fork项目(sti-233)提供的预构建 Bilix 更新<\/string>' ./BiliRoamingX/patches/src/main/resources/bilibili/host/values/strings.xml
          sed -i '/    <string name="biliroaming_usage_hint_message">欢迎使用基于ReVanced方案的修改版哔哩哔哩。以下几点说明请仔细阅读：\\n\\n1. 本修改方案完全开源免费，谨防被骗。\\n2. 本修改版不使用Xposed框架，追求极致性能。\\n3. 请勿在B站任何地方暗示\/提及\/宣传本修改版。\\n4. 设置入口：我的 -> 设置 -> 哔哩漫游X。<\/string>/c\    <string name="biliroaming_usage_hint_message">欢迎使用基于ReVanced方案的修改版哔哩哔哩。以下几点说明请仔细阅读：\\n\\n1. 本修改方案完全开源免费，谨防被骗。\\n2. 本修改版不使用Xposed框架，追求极致性能。\\n3. 请勿在B站任何地方暗示\/提及\/宣传本修改版，否则将会被拉入黑名单，模块所有功能将被停用。\\n4. 设置入口：我的 -> 设置 -> BiliRoamingX。<\/string>' ./BiliRoamingX/patches/src/main/resources/bilibili/host/values/strings.xml
          awk '/<resources>/ { print; print "    <string name=\"biliroaming_custom_update_source_title\">自定义更新源</string>\n    <string name=\"biliroaming_custom_update_source_summary\">不同源间可能签名不同,请谨慎选择 !</string>"; next }1' ./BiliRoamingX/patches/src/main/resources/bilibili/host/values/strings.xml > temp.xml && mv temp.xml ./BiliRoamingX/patches/src/main/resources/bilibili/host/values/strings.xml
          echo "-"
          echo "./BiliRoamingX/patches/src/main/resources/bilibili/host/values/strings_raw.xml"
          echo "-"
          sed -i 's#    <string name="biliroaming_project_url">https://github.com/BiliRoamingX/BiliRoamingX</string>#    <string name="biliroaming_project_url">https://github.com/sti-233/Bilix-PreBuilds</string>#' ./BiliRoamingX/patches/src/main/resources/bilibili/host/values/strings_raw.xml
          sed -i 's#    <string name="biliroaming_tg_url">https://t.me/bb_show</string>#    <string name="biliroaming_tg_url">https://t.me/Aniruf_x</string>#' ./BiliRoamingX/patches/src/main/resources/bilibili/host/values/strings_raw.xml
          sed -i 's#    <string name="biliroaming_feedback_url">https://github.com/BiliRoamingX/BiliRoamingX/issues/new/choose</string>#    <string name="biliroaming_feedback_url">https://github.com/sti-233/Bilix-PreBuilds/issues/new</string>#' ./BiliRoamingX/patches/src/main/resources/bilibili/host/values/strings_raw.xml
          awk '/<resources>/ { print; print "    <string name=\"biliroaming_release_host\">https://api.github.com/repos/sti-233/Bilix-PreBuilds/releases</string>\n    <string name=\"biliroaming_nightly_host\">https://api.github.com/repos/sti-233/Bilix-PreBuilds/releases/tag/Nightly</string>\n    <string name=\"biliroaming_original_host\">https://api.github.com/repos/BiliRoamingX/BiliRoamingX-PreBuilds/releases</string>"; next }1' ./BiliRoamingX/patches/src/main/resources/bilibili/host/values/strings_raw.xml > temp.xml && mv temp.xml ./BiliRoamingX/patches/src/main/resources/bilibili/host/values/strings_raw.xml
          echo "-"
          echo "./BiliRoamingX/integrations/app/src/main/java/app/revanced/bilibili/settings/fragments/MiscFragment.kt"
          echo "-"
          sed -i '/^[[:space:]]*Utils\.isHd()/!b;n;c\        //}' ./BiliRoamingX/integrations/app/src/main/java/app/revanced/bilibili/settings/fragments/MiscFragment.kt
          sed -i '0,/        disablePreference(/s//        \/\/disablePreference(/' ./BiliRoamingX/integrations/app/src/main/java/app/revanced/bilibili/settings/fragments/MiscFragment.kt
          sed -i '/            key = Settings.CustomUpdate.key,/c\            //key = Settings.CustomUpdate.key,' ./BiliRoamingX/integrations/app/src/main/java/app/revanced/bilibili/settings/fragments/MiscFragment.kt
          sed -i '/            { Utils.getString("biliroaming_custom_update_only_64") } to { !isOsArchArm64 },/c\            //{ Utils.getString("biliroaming_custom_update_only_64") } to { !isOsArchArm64 },' ./BiliRoamingX/integrations/app/src/main/java/app/revanced/bilibili/settings/fragments/MiscFragment.kt
          sed -i '/            { Utils.getString("biliroaming_custom_update_invalid_sig") } to { !isPrebuilt }/c\            //{ Utils.getString("biliroaming_custom_update_invalid_sig") } to { !isPrebuilt }' ./BiliRoamingX/integrations/app/src/main/java/app/revanced/bilibili/settings/fragments/MiscFragment.kt
          sed -i '0,/        )/s//        \/\/)/' ./BiliRoamingX/integrations/app/src/main/java/app/revanced/bilibili/settings/fragments/MiscFragment.kt
          sed -i '/\ \ \ \ \ \ \ \ disablePreference(Settings.Skin.key, PrefsDisableReason.AppVersion) {/c\        //disablePreference(Settings.Skin.key, PrefsDisableReason.AppVersion) {' ./BiliRoamingX/integrations/app/src/main/java/app/revanced/bilibili/settings/fragments/MiscFragment.kt
          sed -i '/            Utils.isHd()/c\            //Utils.isHd()' ./BiliRoamingX/integrations/app/src/main/java/app/revanced/bilibili/settings/fragments/MiscFragment.kt
          echo "-"
          echo "./BiliRoamingX/patches/src/main/resources/bilibili/host/values/arrays.xml"
          echo "-"
          awk '/<resources>/ { print; print "    <string-array name=\"biliroaming_update_source_entries\">\n        <item>Bilix-Release</item>\n        <item>Bilix-Nightly</item>\n        <item>BiliRoamingX/BiliRoamingX-Prebuilds</item>\n    </string-array>\n    <string-array name=\"biliroaming_update_source_values\">\n        <item>@string/biliroaming_release_host</item>\n        <item>@string/biliroaming_nightly_host</item>\n        <item>@string/biliroaming_original_host</item>\n    </string-array>\n    <string-array name=\"biliroaming_update_source_summaries\">\n        <item>由 sti-233 (本fork) 提供的更新源 较慢</item>\n        <item>由 sti-233 (本fork) 提供的更新源 快</item>\n        <item>由  zjns (bb_show) 提供的更新源 很慢 (签名不同 !)</item>\n    </string-array>"; next }1' ./BiliRoamingX/patches/src/main/resources/bilibili/host/values/arrays.xml > temp.xml && mv temp.xml ./BiliRoamingX/patches/src/main/resources/bilibili/host/values/arrays.xml
          echo "-"
          echo "./BiliRoamingX/patches/src/main/resources/bilibili/xml/biliroaming_setting_misc.xml"
          echo "-"
          awk '/android:title="@string\/biliroaming_custom_update_title" \/>/ { print; print "        <tv.danmaku.bili.widget.preference.BLRadioGroupEntrancePreference\n            android:dependency=\"custom_update\"\n            android:fragment=\"app.revanced.bilibili.settings.fragments.UpdateSettingFragment\"\n            android:key=\"custom_update_source\"\n            android:persistent=\"true\"\n            android:title=\"@string/biliroaming_custom_update_source_title\"\n            app:migration_settings_type=\"none\"\n            app:radioDefaultValue=\"@string/biliroaming_release_host\"\n            app:radioEntries=\"@array/biliroaming_update_source_entries\"\n            app:radioEntryValues=\"@array/biliroaming_update_source_values\" />"; next }1' ./BiliRoamingX/patches/src/main/resources/bilibili/xml/biliroaming_setting_misc.xml > temp.xml && mv temp.xml ./BiliRoamingX/patches/src/main/resources/bilibili/xml/biliroaming_setting_misc.xml
          echo "-"
          echo "./BiliRoamingX/patches/src/main/kotlin/app/revanced/patches/bilibili/misc/settings/patch/SettingsResourcePatch.kt"
          echo "-"
          awk '/    private val xmls = arrayOf\(/ { print; print "        \"biliroaming_setting_custom_update_source.xml\","; next }1' ./BiliRoamingX/patches/src/main/kotlin/app/revanced/patches/bilibili/misc/settings/patch/SettingsResourcePatch.kt > temp.kt && mv temp.kt ./BiliRoamingX/patches/src/main/kotlin/app/revanced/patches/bilibili/misc/settings/patch/SettingsResourcePatch.kt
          echo "-"
          echo "./BiliRoamingX/integrations/app/src/main/java/app/revanced/bilibili/settings/fragments/fragments.kt"
          echo "-"
          echo -e "\n@SettingFragment(\"biliroaming_setting_custom_update_source\")\nclass UpdateSettingFragment : BiliRoamingBaseSettingFragment()" >> ./BiliRoamingX/integrations/app/src/main/java/app/revanced/bilibili/settings/fragments/fragments.kt
          echo "-"
          echo "./BiliRoamingX/integrations/app/src/main/java/app/revanced/bilibili/settings/Settings.kt"
          echo "-"
          awk '/@JvmField val CustomUpdate = BooleanSetting\(key = "custom_update", defValue = true\)/ { print; print "    @JvmField val UpdateApi = StringSetting(key = \"custom_update_source\", needReboot = true)"; next }1' ./BiliRoamingX/integrations/app/src/main/java/app/revanced/bilibili/settings/Settings.kt > temp.kt && mv temp.kt ./BiliRoamingX/integrations/app/src/main/java/app/revanced/bilibili/settings/Settings.kt
          echo "Recompose Succeed"
      # push resource
      - name: Push composed Resource
        run: |
          cd ./
          mkdir -p composed
          cp ./BiliRoamingX/patches/src/main/resources/bilibili/host/values/strings.xml ./composed/strings.xml
          cp ./BiliRoamingX/patches/src/main/resources/bilibili/host/values/strings_raw.xml ./composed/strings_raw.xml
          cp ./BiliRoamingX/integrations/app/src/main/java/app/revanced/bilibili/settings/fragments/MiscFragment.kt ./composed/MiscFragment.kt
          cp ./BiliRoamingX/patches/src/main/resources/bilibili/host/values/arrays.xml ./composed/arrays.xml
          cp ./BiliRoamingX/patches/src/main/resources/bilibili/xml/biliroaming_setting_misc.xml ./composed/biliroaming_setting_misc.xml
          cp ./BiliRoamingX/patches/src/main/kotlin/app/revanced/patches/bilibili/misc/settings/patch/SettingsResourcePatch.kt ./composed/SettingsResourcePatch.kt
          cp ./BiliRoamingX/integrations/app/src/main/java/app/revanced/bilibili/settings/fragments/fragments.kt ./composed/fragments.kt
          cp ./BiliRoamingX/integrations/app/src/main/java/app/revanced/bilibili/settings/Settings.kt ./composed/Settings.kt
          rm -r ./BiliRoamingX
          rm -r ./Bilix-PreBuilds
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add composed/strings.xml
          git add composed/strings_raw.xml
          git add composed/MiscFragment.kt
          git add composed/arrays.xml
          git add composed/biliroaming_setting_misc.xml
          git add composed/SettingsResourcePatch.kt
          git add composed/fragments.kt
          git add composed/Settings.kt
          git commit -m "Push resource"
          git push
        continue-on-error: true
