name: Lspatch

on:
  workflow_dispatch:

jobs:
  Merge:
    name: Lspatch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Get original resource
        run: |
          wget https://github.com/sti-233/Bilix-PreBuilds/releases/download/Nightly-android-Nightly/Bilix-cn-Nightly@Aniruf_x.apk
          java -jar lspatch.jar -m lspatch.apk --sigbypasslv 2 -o "test" Bilix-cn-Nightly@Aniruf_x.apk

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: Bilix-cn-Nightly@Aniruf_x
          path: 'test'
